<?php

namespace Modules\FNB\Providers;

use Illuminate\Support\ServiceProvider;
use Modules\FNB\Models\FNBQrTemplateLogoTable;
use Modules\FNB\Repositories\Branch\BranchRepository;
use Modules\FNB\Repositories\Branch\BranchRepositoryInterface;
use Modules\FNB\Repositories\CodeGenerator\CodeGeneratorRepository;
use Modules\FNB\Repositories\CodeGenerator\CodeGeneratorRepositoryInterface;
use Modules\FNB\Repositories\Config\ConfigRepository;
use Modules\FNB\Repositories\Config\ConfigRepositoryInterface;
use Modules\FNB\Repositories\ConfigColumn\ConfigColumnRepository;
use Modules\FNB\Repositories\ConfigColumn\ConfigColumnRepositoryInterface;
use Modules\FNB\Repositories\ConfigPrintBill\ConfigPrintBillRepository;
use Modules\FNB\Repositories\ConfigPrintBill\ConfigPrintBillRepositoryInterface;
use Modules\FNB\Repositories\Customer\CustomerRepository;
use Modules\FNB\Repositories\Customer\CustomerRepositoryInterface;
use Modules\FNB\Repositories\CustomerBranchMoney\CustomerBranchMoneyRepository;
use Modules\FNB\Repositories\CustomerBranchMoney\CustomerBranchMoneyRepositoryInterface;
use Modules\FNB\Repositories\CustomerDebt\CustomerDebtRepository;
use Modules\FNB\Repositories\CustomerDebt\CustomerDebtRepositoryInterface;
use Modules\FNB\Repositories\CustomerGroup\CustomerGroupRepository;
use Modules\FNB\Repositories\CustomerGroup\CustomerGroupRepositoryInterface;
use Modules\FNB\Repositories\CustomerServiceCard\CustomerServiceCardRepository;
use Modules\FNB\Repositories\CustomerServiceCard\CustomerServiceCardRepositoryInterface;
use Modules\FNB\Repositories\DiscountCause\DiscountCauseRepository;
use Modules\FNB\Repositories\DiscountCause\DiscountCauseRepositoryInterface;
use Modules\FNB\Repositories\FNBAreas\FNBAreasRepository;
use Modules\FNB\Repositories\FNBAreas\FNBAreasRepositoryInterface;
use Modules\FNB\Repositories\FNBCustomer\FNBCustomerRepository;
use Modules\FNB\Repositories\FNBCustomer\FNBCustomerRepositoryInterface;
use Modules\FNB\Repositories\FNBCustomerRequest\FNBCustomerRequestRepository;
use Modules\FNB\Repositories\FNBCustomerRequest\FNBCustomerRequestRepositoryInterface;
use Modules\FNB\Repositories\FNBQrCode\FNBQrCodeRepository;
use Modules\FNB\Repositories\FNBQrCode\FNBQrCodeRepositoryInterface;
use Modules\FNB\Repositories\FNBQrCodeScan\FNBQrCodeScanRepository;
use Modules\FNB\Repositories\FNBQrCodeScan\FNBQrCodeScanRepositoryInterface;
use Modules\FNB\Repositories\FNBQrTemplate\FNBQrTemplateRepository;
use Modules\FNB\Repositories\FNBQrTemplate\FNBQrTemplateRepositoryInterface;
use Modules\FNB\Repositories\FNBQrTemplateFont\FNBQrTemplateFontRepository;
use Modules\FNB\Repositories\FNBQrTemplateFont\FNBQrTemplateFontRepositoryInterface;
use Modules\FNB\Repositories\FNBQrTemplateFrames\FNBQrTemplateFramesRepository;
use Modules\FNB\Repositories\FNBQrTemplateFrames\FNBQrTemplateFramesRepositoryInterface;
use Modules\FNB\Repositories\FNBQrTemplateLogo\FNBQrTemplateLogoRepository;
use Modules\FNB\Repositories\FNBQrTemplateLogo\FNBQrTemplateLogoRepositoryInterface;
use Modules\FNB\Repositories\FNBTable\FNBTableRepository;
use Modules\FNB\Repositories\FNBTable\FNBTableRepositoryInterface;
use Modules\FNB\Repositories\InventoryOutput\InventoryOutputRepository;
use Modules\FNB\Repositories\InventoryOutput\InventoryOutputRepositoryInterface;
use Modules\FNB\Repositories\InventoryOutputDetail\InventoryOutputDetailRepository;
use Modules\FNB\Repositories\InventoryOutputDetail\InventoryOutputDetailRepositoryInterface;
use Modules\FNB\Repositories\Order\OrderRepository;
use Modules\FNB\Repositories\Order\OrderRepositoryInterface;
use Modules\FNB\Repositories\OrderApp\OrderAppRepo;
use Modules\FNB\Repositories\OrderApp\OrderAppRepoInterface;
use Modules\FNB\Repositories\OrderCommission\OrderCommissionRepository;
use Modules\FNB\Repositories\OrderCommission\OrderCommissionRepositoryInterface;
use Modules\FNB\Repositories\OrderDetail\OrderDetailRepository;
use Modules\FNB\Repositories\OrderDetail\OrderDetailRepositoryInterface;
use Modules\FNB\Repositories\PaymentMethod\PaymentMethodRepository;
use Modules\FNB\Repositories\PaymentMethod\PaymentMethodRepositoryInterface;
use Modules\FNB\Repositories\PrintBillLog\PrintBillLogRepository;
use Modules\FNB\Repositories\PrintBillLog\PrintBillLogRepositoryInterface;
use Modules\FNB\Repositories\Product\ProductRepository;
use Modules\FNB\Repositories\Product\ProductRepositoryInterface;
use Modules\FNB\Repositories\ProductAttribute\ProductAttributeRepository;
use Modules\FNB\Repositories\ProductAttribute\ProductAttributeRepositoryInterface;
use Modules\FNB\Repositories\ProductAttributeGroup\ProductAttributeGroupRepository;
use Modules\FNB\Repositories\ProductAttributeGroup\ProductAttributeGroupRepositoryInterface;
use Modules\FNB\Repositories\ProductBranchPrice\ProductBranchPriceRepository;
use Modules\FNB\Repositories\ProductBranchPrice\ProductBranchPriceRepositoryInterface;
use Modules\FNB\Repositories\ProductCategory\ProductCategoryRepository;
use Modules\FNB\Repositories\ProductCategory\ProductCategoryRepositoryInterface;
use Modules\FNB\Repositories\ProductChild\ProductChildRepository;
use Modules\FNB\Repositories\ProductChild\ProductChildRepositoryInterface;
use Modules\FNB\Repositories\ProductInventory\ProductInventoryRepository;
use Modules\FNB\Repositories\ProductInventory\ProductInventoryRepositoryInterface;
use Modules\FNB\Repositories\ProductTopping\ProductToppingRepository;
use Modules\FNB\Repositories\ProductTopping\ProductToppingRepositoryInterface;
use Modules\FNB\Repositories\PromotionDailyTime\PromotionDailyTimeRepository;
use Modules\FNB\Repositories\PromotionDailyTime\PromotionDailyTimeRepositoryInterface;
use Modules\FNB\Repositories\PromotionDateTime\PromotionDateTimeRepository;
use Modules\FNB\Repositories\PromotionDateTime\PromotionDateTimeRepositoryInterface;
use Modules\FNB\Repositories\PromotionDetail\PromotionDetailRepository;
use Modules\FNB\Repositories\PromotionDetail\PromotionDetailRepositoryInterface;
use Modules\FNB\Repositories\PromotionMaster\PromotionMasterRepository;
use Modules\FNB\Repositories\PromotionMaster\PromotionMasterRepositoryInterface;
use Modules\FNB\Repositories\PromotionMonthlyTime\PromotionMonthlyTimeRepository;
use Modules\FNB\Repositories\PromotionMonthlyTime\PromotionMonthlyTimeRepositoryInterface;
use Modules\FNB\Repositories\PromotionObjectApply\PromotionObjectApplyRepository;
use Modules\FNB\Repositories\PromotionObjectApply\PromotionObjectApplyRepositoryInterface;
use Modules\FNB\Repositories\PromotionWeeklyTime\PromotionWeeklyTimeRepository;
use Modules\FNB\Repositories\PromotionWeeklyTime\PromotionWeeklyTimeRepositoryInterface;
use Modules\FNB\Repositories\Province\ProvinceRepository;
use Modules\FNB\Repositories\Province\ProvinceRepositoryInterface;
use Modules\FNB\Repositories\Receipt\ReceiptRepository;
use Modules\FNB\Repositories\Receipt\ReceiptRepositoryInterface;
use Modules\FNB\Repositories\ReceiptDetail\ReceiptDetailRepository;
use Modules\FNB\Repositories\ReceiptDetail\ReceiptDetailRepositoryInterface;
use Modules\FNB\Repositories\ReviewList\ReviewListRepository;
use Modules\FNB\Repositories\ReviewList\ReviewListRepositoryInterface;
use Modules\FNB\Repositories\ReviewListDetail\ReviewListDetailRepository;
use Modules\FNB\Repositories\ReviewListDetail\ReviewListDetailRepositoryInterface;
use Modules\FNB\Repositories\Room\RoomRepository;
use Modules\FNB\Repositories\Room\RoomRepositoryInterface;
use Modules\FNB\Repositories\Service\ServiceRepository;
use Modules\FNB\Repositories\Service\ServiceRepositoryInterface;
use Modules\FNB\Repositories\ServiceBranchPrice\ServiceBranchPriceRepository;
use Modules\FNB\Repositories\ServiceBranchPrice\ServiceBranchPriceRepositoryInterface;
use Modules\FNB\Repositories\ServiceCard\ServiceCardRepository;
use Modules\FNB\Repositories\ServiceCard\ServiceCardRepositoryInterface;
use Modules\FNB\Repositories\ServiceCardList\ServiceCardListRepository;
use Modules\FNB\Repositories\ServiceCardList\ServiceCardListRepositoryInterface;
use Modules\FNB\Repositories\ServiceMaterial\ServiceMaterialRepository;
use Modules\FNB\Repositories\ServiceMaterial\ServiceMaterialRepositoryInterface;
use Modules\FNB\Repositories\SmsConfig\SmsConfigRepository;
use Modules\FNB\Repositories\SmsConfig\SmsConfigRepositoryInterface;
use Modules\FNB\Repositories\SpaInfo\SpaInfoRepository;
use Modules\FNB\Repositories\SpaInfo\SpaInfoRepositoryInterface;
use Modules\FNB\Repositories\Staff\StaffRepository;
use Modules\FNB\Repositories\Staff\StaffRepositoryInterface;
use Modules\FNB\Repositories\Voucher\VoucherRepository;
use Modules\FNB\Repositories\Voucher\VoucherRepositoryInterface;
use Modules\FNB\Repositories\Warehouse\WarehouseRepository;
use Modules\FNB\Repositories\Warehouse\WarehouseRepositoryInterface;
use Modules\FNB\Repositories\FNBCustomerReview\FNBCustomerReviewRepositoryInterface;
use Modules\FNB\Repositories\FNBCustomerReview\FNBCustomerReviewRepository;
use Modules\FNB\Repositories\FNBRequest\FNBRequestRepositoryInterface;
use Modules\FNB\Repositories\FNBRequest\FNBRequestRepository;


class RepositoryServiceProvider extends ServiceProvider
{
    /**
     * Register any application services.
     *
     * @return void
     */
    public function register()
    {
        $this->app->singleton(PromotionMasterRepositoryInterface::class,PromotionMasterRepository::class);
        $this->app->singleton(ProductRepositoryInterface::class,ProductRepository::class);
        $this->app->singleton(ProductChildRepositoryInterface::class,ProductChildRepository::class);
        $this->app->singleton(ProductToppingRepositoryInterface::class,ProductToppingRepository::class);
        $this->app->singleton(FNBAreasRepositoryInterface::class,FNBAreasRepository::class);
        $this->app->singleton(FNBCustomerRepositoryInterface::class,FNBCustomerRepository::class);
        $this->app->singleton(FNBQrCodeScanRepositoryInterface::class,FNBQrCodeScanRepository::class);
        $this->app->singleton(FNBQrCodeRepositoryInterface::class,FNBQrCodeRepository::class);
        $this->app->singleton(FNBQrTemplateFontRepositoryInterface::class,FNBQrTemplateFontRepository::class);
        $this->app->singleton(FNBQrTemplateFramesRepositoryInterface::class,FNBQrTemplateFramesRepository::class);
        $this->app->singleton(FNBQrTemplateRepositoryInterface::class,FNBQrTemplateRepository::class);
        $this->app->singleton(FNBTableRepositoryInterface::class,FNBTableRepository::class);
        $this->app->singleton(ConfigColumnRepositoryInterface::class,ConfigColumnRepository::class);
        $this->app->singleton(BranchRepositoryInterface::class,BranchRepository::class);
        $this->app->singleton(StaffRepositoryInterface::class,StaffRepository::class);
        $this->app->singleton(ProductAttributeGroupRepositoryInterface::class,ProductAttributeGroupRepository::class);
        $this->app->singleton(FNBQrTemplateLogoRepositoryInterface::class,FNBQrTemplateLogoRepository::class);
        $this->app->singleton(ConfigRepositoryInterface::class,ConfigRepository::class);
        $this->app->singleton(CustomerGroupRepositoryInterface::class,CustomerGroupRepository::class);
        $this->app->singleton(DiscountCauseRepositoryInterface::class,DiscountCauseRepository::class);
        $this->app->singleton(PaymentMethodRepositoryInterface::class,PaymentMethodRepository::class);
        $this->app->singleton(ProvinceRepositoryInterface::class,ProvinceRepository::class);
        $this->app->singleton(OrderRepositoryInterface::class,OrderRepository::class);
        $this->app->singleton(CustomerRepositoryInterface::class,CustomerRepository::class);
        $this->app->singleton(CustomerBranchMoneyRepositoryInterface::class,CustomerBranchMoneyRepository::class);
        $this->app->singleton(CustomerServiceCardRepositoryInterface::class,CustomerServiceCardRepository::class);
        $this->app->singleton(RoomRepositoryInterface::class,RoomRepository::class);
        $this->app->singleton(ServiceBranchPriceRepositoryInterface::class,ServiceBranchPriceRepository::class);
        $this->app->singleton(ProductCategoryRepositoryInterface::class,ProductCategoryRepository::class);
        $this->app->singleton(ProductBranchPriceRepositoryInterface::class,ProductBranchPriceRepository::class);
        $this->app->singleton(PromotionDailyTimeRepositoryInterface::class,PromotionDailyTimeRepository::class);
        $this->app->singleton(PromotionDateTimeRepositoryInterface::class,PromotionDateTimeRepository::class);
        $this->app->singleton(PromotionDetailRepositoryInterface::class,PromotionDetailRepository::class);
        $this->app->singleton(PromotionMonthlyTimeRepositoryInterface::class,PromotionMonthlyTimeRepository::class);
        $this->app->singleton(PromotionObjectApplyRepositoryInterface::class,PromotionObjectApplyRepository::class);
        $this->app->singleton(PromotionWeeklyTimeRepositoryInterface::class,PromotionWeeklyTimeRepository::class);
        $this->app->singleton(ProductAttributeRepositoryInterface::class,ProductAttributeRepository::class);
        $this->app->singleton(OrderAppRepoInterface::class,OrderAppRepo::class);
        $this->app->singleton(VoucherRepositoryInterface::class,VoucherRepository::class);
        $this->app->singleton(SpaInfoRepositoryInterface::class,SpaInfoRepository::class);
        $this->app->singleton(ServiceCardListRepositoryInterface::class,ServiceCardListRepository::class);
        $this->app->singleton(ServiceCardRepositoryInterface::class,ServiceCardRepository::class);
        $this->app->singleton(WarehouseRepositoryInterface::class,WarehouseRepository::class);
        $this->app->singleton(InventoryOutputRepositoryInterface::class,InventoryOutputRepository::class);
        $this->app->singleton(InventoryOutputDetailRepositoryInterface::class,InventoryOutputDetailRepository::class);
        $this->app->singleton(ProductInventoryRepositoryInterface::class,ProductInventoryRepository::class);
        $this->app->singleton(CodeGeneratorRepositoryInterface::class,CodeGeneratorRepository::class);
        $this->app->singleton(SmsConfigRepositoryInterface::class,SmsConfigRepository::class);
        $this->app->singleton(CustomerDebtRepositoryInterface::class,CustomerDebtRepository::class);
        $this->app->singleton(OrderCommissionRepositoryInterface::class,OrderCommissionRepository::class);
        $this->app->singleton(ReceiptRepositoryInterface::class,ReceiptRepository::class);
        $this->app->singleton(ReceiptDetailRepositoryInterface::class,ReceiptDetailRepository::class);
        $this->app->singleton(OrderDetailRepositoryInterface::class,OrderDetailRepository::class);
        $this->app->singleton(ConfigPrintBillRepositoryInterface::class,ConfigPrintBillRepository::class);
        $this->app->singleton(PrintBillLogRepositoryInterface::class,PrintBillLogRepository::class);
        $this->app->singleton(ServiceRepositoryInterface::class,ServiceRepository::class);
        $this->app->singleton(ServiceMaterialRepositoryInterface::class,ServiceMaterialRepository::class);
        $this->app->singleton(FNBCustomerRequestRepositoryInterface::class,FNBCustomerRequestRepository::class);
        $this->app->singleton(FNBCustomerReviewRepositoryInterface::class,FNBCustomerReviewRepository::class);
        $this->app->singleton(FNBRequestRepositoryInterface::class,FNBRequestRepository::class);
        $this->app->singleton(ReviewListRepositoryInterface::class,ReviewListRepository::class);
        $this->app->singleton(ReviewListDetailRepositoryInterface::class,ReviewListDetailRepository::class);
    }
}